name: civis10-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - requests=2.28.1
  - beautifulsoup4=4.11.1
  - sentence-transformers=2.2.2
  - vaderSentiment=3.3.2
  - textblob=0.15.3
  - spacy=3.4.1
  - numpy=1.24.0
  - pip
  - pip:
      - transformers